project:
  type: website
  output-dir: docs

website:
  title: "Paula Muñoz"
  favicon: images/logo_paula.png
  navbar:
    title: false
    logo: images/logo_paula.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - posts.qmd



format:
  html:
    theme: 
        - mystyles.scss
    mainfont: Poppins
    toc: true

editor: visual

