project:
  type: website
  output-dir: docs

website:
  title: "Paula Muñoz"
  favicon: images/logo_paula.png
  navbar:
    title: false
    logo: images/logo_paula.png
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
      - about.qmd
  page-footer: 
    background: light
    left: 
      - "Copyright 2023, Paula Munoz"
      



format:
  html:
    theme: 
        - mystyles.scss
    mainfont: Poppins
    toc: true

editor: visual

