---
title: "My Experience & Education"
---

I have over 5 years of experience applying Data and Business Analytics techniques to support decision-making and process improvement.

## **Experience**

#### **Data Visualization and Analytics Consultant,** March 2022 - Present 

#### [Cleartelligence](https://www.cleartelligence.com/)

-   Translate complex business issues into structured analysis.

-   Develop rich interactive visualizations, that are intuitive, easy to use and understand using Tableau, Looker Studio and Power BI.

-   Prepare, blend and cleanse data.

-   Create robust documentation of solutions and operating procedures to transition support.

-   Proficient in training business professionals on Tableau and Power Query usage.

#### **Adjunct Faculty Member,** Spring 2023 

#### Endicott College

-   Taught Data Mining & Business Intelligence (ITS-570) course to MBA students.

-   Developed and delivered engaging lectures and class discussions.

-   Trained students on how to use Advanced Excel for data analysis, Tableau Prep Builder and SQL for data Wrangling and Tableau for Data Visualization and Presentations.

#### **Product Analyst \| Data Scientist \| Manager Data Solutions,** 2017-2022 

#### NetNumber - Global Data Services

-   Responsible for providing time sensitive analysis and implementing intuitive dashboards and ad-hoc reports to support the day-to-day decision-making needs regarding NetNumber's Global Data Services.

-   Reported to the VP of Operations and COO.

-   Hired, trained and mentored two Junior Data Analysts.

-   Partnered directly with the executive team as the first data hire to formulate and report on Global Data Services KPIs using Tableau.

-   Designed Profit margin analysis Dashboards to identify savings opportunities, high risk customers, and assess new pricing

## **Education**

#### **MBA,** 2026

*Questrom School of Business - Boston University*

#### **MSc in Telecommunications Systems Management,** 2016

*Northeastern University*

#### **BSc in Information Technology, 2012**

*University of Massachusetts*

#### **BSc in Electronics' Engineering, 2007**

*Santo Tomás de Aquino University*
